export const CHANGE_SIGN_UP_FORM = 'CHANGE_SIGN_UP_FORM'
export const CHANGE_SIGN_IN_FORM = 'CHANGE_SIGN_IN_FORM'
export const USER_SIGN_UP = 'USER_SIGN_UP'
export const USER_SIGN_IN = 'USER_SIGN_IN'
